AusDTO/gov-au-beta

- app/controllers/editorial/nodes_controller.rb
- app/controllers/nodes_controller.rb
- app/helpers/nodes_helper.rb
Recent clashing changes to templates and editorial controllers resulted in editorial/nodes/show throwing an exception (SITES-384). This fixes that.
> Fix for editorial/nodes/show

- app/controllers/editorial/nodes_controller.rb
- app/controllers/editorial/submissions_controller.rb
- app/forms/node_metadata_form.rb
- app/views/application/_navbar_part.html.haml
- app/views/application/_page_actions.html.haml
- app/views/editorial/nodes/edit.html.haml
- app/views/editorial/nodes/show.html.haml
- app/views/sections/_menu.html.haml
- config/breadcrumbs.rb
- spec/controllers/editorial/submissions_controller_spec.rb
- spec/fabricators/section.rb
- spec/features/editing_content_spec.rb
- spec/features/editing_node_metadata_spec.rb
- spec/support/shared_examples_for_xss.rb
**DO NOT MERGE UNTIL AFTER #180**
Obviously this is not the best user experience possible but it makes it possible to change node order.
> Allow an author to edit node metadata, including child order

- app/controllers/admin/departments_controller.rb
- app/controllers/admin/ministers_controller.rb
- spec/controllers/admin/department_controller_spec.rb
- spec/controllers/admin/ministers_controller_spec.rb
As per: https://govausites.atlassian.net/browse/SITES-391
Fix: updated #find_resource method for admin department and minister controllers.
> Fixed resource paths for admin sections

- app/models/node.rb
- app/validators/ancestry_depth_validator.rb
- app/validators/non_recursive_ancestry_validator.rb
- spec/models/general_content_spec.rb
- spec/validators/ancestry_depth_validator_spec.rb
- spec/validators/non_recursive_ancestry_validator_spec.rb
Validations were tested separately, but on the actual model, if you set a circular ancestry, the ancestry_depth validation would overflow. I've fixed that and introduced a spec on one of the concrete node types (GeneralContent).
See notes on https://govausites.atlassian.net/browse/SITES-355
> Dealt with feedback from SITES-355.

- CHANGELOG.md
- app/controllers/categories_controller.rb
- app/views/categories/infrastructure_and_telecommunications.html.erb
- config/breadcrumbs.rb
- config/routes.rb
- spec/controllers/categories_controller_spec.rb
Rough-as-guts rip of static content from prototype.
I have set up a categories controller but it just has actions and mostly static view. 
I set up the route to match what we will likely have once we have dynamic content. 
Breadcrumb is parented off root as per prototype.
> Hard-coded infrastructure & comms category - SITES-411

- CHANGELOG.md
- app/models/node.rb
- db/seeds.rb
- spec/models/node_spec.rb
Note: using find_by for name on a Node object actually queries the name column rather than `content[:name]`.
> [SITES-425] - Correctly determine if a node with a given name exists

- CHANGELOG.md
- app/controllers/nodes_controller.rb
- app/views/templates/root_node.html.haml
- config/categories.yml
- config/initializers/categories.rb
- spec/features/home_page.rb
Static categories on the homepage as per the prototype. 
I've put the category info into a YAML file which populates an array of OpenStruct objects - so we should later be able to swap out the static data for model instances (once we implement categories in the DB).
> Static categories

- app/assets/stylesheets/_calendar-callout.scss
- app/assets/stylesheets/_calendar-table.scss
- app/assets/stylesheets/_sort-tabs.scss
- app/assets/stylesheets/application.scss
- app/views/templates/custom/public_holidays_qld.html.erb
- app/views/templates/custom/public_holidays_tas.html.erb
This PR adds static versions of Public holidays pages for Tasmania and Queensland as well as the required css. All 3 components on the page have custom css as they are not yet in the UI Kit.
Sort tabs - This feature is in UI Kit current sprint (https://github.com/AusDTO/gov-au-ui-kit/issues/147)
Calendar callout - I have sent a PR for this to UI Kit (https://github.com/AusDTO/gov-au-ui-kit/pull/191)
Calendar table - I have sent a PR for this to UI Kit (https://github.com/AusDTO/gov-au-ui-kit/pull/190)
> Feature/public holiday pages [SITES-407]

- app/views/news/index.html.haml
- app/views/templates/news_article.html.haml
Fixes the view of the distribution tags on news articles to look right:
Also improved the semantic markup for the `/news` page's usage of definition lists.
> fix viewing news tags on article pages

- app/controllers/nodes_controller.rb
- app/models/node.rb
Removes the published scope to make RootNode.first work as intended.
> remove published scope which was messing with RootNode resolution

- CHANGELOG.md
- app/controllers/news_controller.rb
- app/models/news_article.rb
- app/models/submission.rb
- app/views/news/index.html.haml
- db/migrate/20160722043604_add_published_at_datetime_to_node.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/news_controller_spec.rb
Addresses comments left on SITES-364, specifically:
* Lets add a published_at to Node
* Order by published_at desc on news index page
* Remove the "Topics" text preceding the section labels
> [SITES-364] Fix/news published details

- app/controllers/editorial/news_controller.rb
- app/controllers/editorial/submissions_controller.rb
- app/helpers/nodes_helper.rb
- app/models/news_article.rb
- app/models/node.rb
- app/views/application/_navbar_part.html.haml
- app/views/departments/index.html.haml
- app/views/editorial/nodes/index.html.haml
- app/views/editorial/nodes/show.html.haml
- app/views/editorial/requests/show.html.haml
- app/views/editorial/sections/show.html.haml
- app/views/layouts/news_article.html.haml
- app/views/layouts/section.html.haml
- app/views/ministers/index.html.haml
- app/views/news/index.html.haml
- app/views/sections/_menu.html.haml
- app/views/templates/news_article.html.haml
- app/views/templates/root_node.html.haml
- app/views/templates/section_home.html.haml
- config/breadcrumbs.rb
- spec/controllers/editorial/news_controller_spec.rb
- spec/controllers/editorial/submissions_controller_spec.rb
- spec/features/controls_spec.rb
- spec/features/creating_content_spec.rb
- spec/features/editing_content_spec.rb
- spec/models/node_spec.rb
- removed `Node#full_path`
- subclasses override `Node#path_elements` if they need custom routing
- all nodes paths generated using a helper that hides *how* path is generated
e.g. `public_node_path(news_article)`
`public_node_path` is the publically-routeable path for the node. It's
currently defined as `nodes_path(path: node.path)`.
> SITES-418 `public_node_path` helper

- app/views/application/_head.html.erb
- app/views/templates/node.html.haml
Fix the metatag wrapping for the description based on short_summary of a node.
> fix rendering of abstract on base node template

- app/models/news_article.rb
- app/models/section.rb
- config/breadcrumbs.rb
- spec/controllers/news_controller_spec.rb
- spec/features/editing_content_spec.rb
- spec/models/node_spec.rb
- spec/models/section_spec.rb
There's a bunch of bootstrapping issues with trying to delegate the name between the section and its home node. So this does it halfway. It's not great but it works.
> [SITES-419][SITES-427] delegate section name and slug to its home node

- app/controllers/editorial/submissions_controller.rb
- app/decorators/request_decorator.rb
- app/decorators/submission_decorator.rb
- app/decorators/user_decorator.rb
- app/models/ability.rb
- app/models/submission.rb
- app/views/application/_signed_in_nav.html.haml
- app/views/editorial/nodes/show.html.haml
- app/views/editorial/requests/new.html.haml
- app/views/editorial/requests/show.html.haml
- app/views/editorial/sections/collaborators.html.haml
- app/views/editorial/submissions/_submissions.haml
- app/views/editorial/submissions/show.haml
- spec/controllers/editorial/submissions_controller_spec.rb
- spec/fabricators/user.rb
SITES-253 Show all submissions on submissions index
SITES-462 Show email if name is missing for user
Some quick fixes to make submissions more useful now that content editors want to allow only certain users to review submissions rather than everyone self-approving. 
The collection shown by editorial/submissions/index wasn't very useful (only showed user's own submissions) - this PR changes it to show all submissions in the section. 
Also, `UserDecorator#full_name` wasn't very useful for the users on our system as none of them have names. (There's no name fields in the signup form, nor in the admin UI). To allow content reviewers to see who has authored submissions, I've changed this to `display_name` and (for the time being) it shows the email if there's no name available.
> Submissions usability fixes

- CHANGELOG.md
- app/controllers/editorial/news_controller.rb
- app/controllers/news_controller.rb
- app/forms/news_article_form.rb
- app/models/section.rb
- app/views/editorial/news/new.html.haml
- app/views/editorial/submissions/_news_article.html.haml
- app/views/news/index.html.haml
- config/breadcrumbs.rb
This PR moves us closer to phasing out news controller & routes.
The details of next steps are described in SITES-466.
This PR will use the `/news` and `/:section/news` routes to display news listings, with the latter filtering by section. For this to be displayed on a page's navbar, an author must create a general content node with the slug of 'news' - in most instances _this has already been done_, which is why this solution assumes this.
Moving forward, these GeneralContent nodes will be phased out for a specific NewsAggegator type. In the interim, the already-existing nodes provide a nice way of exposing the route for a given section, which `routes.rb` takes over.
This PR also includes some foundational plumbing in `section.rb` to manage the create action of a news aggregator on …
> [SITES-403 | SITES-467] Feature/section news index

- app/models/revision_content.rb
- app/views/editorial/submissions/_content.haml
Name & Body are shown first and then all remaining fields are iterated over in lexicographical order.
If we want to control the order of the fields then we'll need to create a union of all the fields of all node types and manually specify the order in the template. And we'd need to remember to update the template whenever a new field is added.
> SITES-438 show all submitted fields in submission

- CHANGELOG.md
- app/assets/stylesheets/_content-listing.scss
- app/assets/stylesheets/_homepage.scss
- app/assets/stylesheets/application.scss
- app/views/departments/index.html.haml
- app/views/devise/confirmations/new.html.haml
- app/views/devise/passwords/edit.html.haml
- app/views/devise/passwords/new.html.haml
- app/views/devise/registrations/edit.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/devise/unlocks/new.html.haml
- app/views/ministers/index.html.haml
- app/views/news/index.html.haml
- app/views/sections/index.html.haml
- app/views/templates/root_node.html.haml
/departments /news /ministers etc. pages links aren't looking as good as they could be:
> Listing page links styling fix

- CHANGELOG.md
- README.md
- app/controllers/editorial/editorial_controller.rb
- app/views/layouts/editorial.html.haml
- bin/deploy-prod.sh
- bin/deploy-staging.sh
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/circle.rb
- spec/features/editorial_version_spec.rb
Adds the deployed tag/sha1 to the editorial footer if one is present.
This is supplied by our deploy process - prod will get both the git tag and sha1, whereas staging will only get the sha1.
> [SITES-343] Feature/commit and tag in footer

- CHANGELOG.md
- app/assets/stylesheets/_homepage.scss
This PR fixes a bug with IE10/11 ignoring box-sizing on flex-box elements. This was causing layout issue on the category list on the homepage. I have also raised this bug with the UI Kit team https://github.com/AusDTO/gov-au-ui-kit/issues/252
Before
After
> [SITES-544] - browser testing IE11 fixes

- app/views/templates/root_node.html.haml
Note: This was fixed but seems to have been lost in a bad merge.
> Fix news date formatting on home page

- CHANGELOG.md
- app/views/layouts/editorial.html.haml
- app/views/layouts/news_article.html.haml
- app/views/layouts/section.html.haml
- app/views/layouts/section_home.html.haml
- app/views/templates/custom/daylight_savings_act.html.erb
- app/views/templates/custom/daylight_savings_nsw.html.erb
- app/views/templates/custom/daylight_savings_qld.html.erb
- app/views/templates/custom/daylight_savings_tas.html.erb
- app/views/templates/custom/daylight_savings_vic.html.erb
- app/views/templates/custom/public_holidays_act.html.erb
- app/views/templates/custom/public_holidays_nsw.html.erb
- app/views/templates/custom/public_holidays_qld.html.erb
- app/views/templates/custom/public_holidays_tas.html.erb
- app/views/templates/custom/public_holidays_vic.html.erb
- app/views/templates/custom/school_holidays_act.html.erb
- app/views/templates/custom/school_holidays_nsw.html.erb
- app/views/templates/custom/school_holidays_qld.html.erb
- app/views/templates/custom/school_holidays_tas.html.erb
- app/views/templates/general_content.html.haml
- app/views/templates/news_article.html.haml
- app/views/templates/node.html.haml
- app/views/templates/section_home.html.haml
The Metadata heading is now correctly shown below the preview.
> SITES-476 Move content-main class to layouts

- CHANGELOG.md
- app/controllers/editorial/editorial_controller.rb
- app/controllers/editorial/nodes_controller.rb
- spec/controllers/editorial/nodes_controller_spec.rb
Programmers' changelog:
* Move the check for valid node types above the constantize call
* Return a 400 error when there's a bad type
* Remove some deprecation warnings in tests
* Remove duplicated tests
> [SITES-542] Whitelist types when creating a node

- .gitignore
- CHANGELOG.md
- Gemfile
- Gemfile.lock
- README.md
- app/views/news/index.html.haml
- app/views/templates/_related_ministers.html.haml
- app/views/templates/_related_sections.html.haml
- app/views/templates/news_article.html.haml
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/sitemap.rb
- lib/tasks/smoke.rake
- spec/features/accessibility_spec.rb
- spec/lib/synergy/cms_import_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
Notes:
* Running `rspec` will test accessibility of a couple of dummy pages
* Running `rake sitemap:create` will create a sitemap of the public site in `public/sitemaps/public.xml` and a dummy editorial sitemap in `public/sitemaps/editorial.xml` as well as the index `public/sitemap.xml`
* Running `ACCESSIBILITY_TEST_SITEMAP='public/sitemaps/public.xml' rake smoke:accessibility` will test accessibility of all pages listed in the sitemap.
* Fixes accessibility issues with the news tags and alt-text for minister images.
> [SITES-554] Add accessibility tests and fix accessibility errors

- CHANGELOG.md
- bin/scrub.rb
No longer assumes column order, and raises error if scrubbing does not occur.
Also now scrub IPs, reset tokens, and confirmation tokens.
> SITES-578 SITES-609 More robust scrubbing

- app/controllers/application_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/departments_controller.rb
- app/controllers/editorial/editorial_controller.rb
- app/controllers/editorial/news_controller.rb
- app/controllers/editorial/nodes_controller.rb
- app/controllers/editorial/requests_controller.rb
- app/controllers/editorial/sections_controller.rb
- app/controllers/editorial/submissions_controller.rb
- app/controllers/ministers_controller.rb
- app/controllers/news_controller.rb
- app/controllers/nodes_controller.rb
- spec/controllers/application_controller_spec.rb
The generated ETAG is automatically busted when a new version of the app
is released.
NOTE: does not cover admin routes.
> SITES-619 generate ETAGs in all show/index requests

- app/controllers/application_controller.rb
- app/controllers/editorial/editorial_controller.rb
- app/decorators/user_decorator.rb
- app/models/ability.rb
- app/models/section.rb
- app/models/section_home.rb
- app/models/user.rb
- app/views/application/_signed_in_nav.html.haml
- spec/models/section_home_spec.rb
- Loading the Section now preloads the home_node for the Section
- ApplicationController#current_user now preloads all of the User roles
Also added a feature to ensure that Section#name is updated when
SectionHome#name is updated. Ideally we can restore the delegate at some
point but Sections are created *before* the SectionHome in the admin
area and they will need to display a name in the meantime.
Fixed related breakages.
> SITES-618 improve editorial index performance

- spec/controllers/application_controller_spec.rb
- spec/fabricators/node.rb
Fixing one wrong instantiation of :node in a test, and renamed node fabricator to `abstract_node`
> SITES-602 Bugfix/node fabricator

- app/assets/stylesheets/application.scss
- app/views/templates/custom/daylight_savings_nt.html.erb
This PR fixes the broken layout on the Norther Territory daylight savings page caused by an open <nav> tag.
> Add closing </nav> tag

- CHANGELOG.md
- config/initializers/devise.rb
- spec/features/enumerating_emails_spec.rb
This stops enumerating email addresses for everything except sign-up. Sign up requires more thought so I figured I'd put up the easy part first.
Note: It's currently using the default devise flash messages. If people have suggestions for better language, I'm all ears.
> [SITES-639] Enable devise paranoia mode

- CHANGELOG.md
- app/renderers/content_markdown.rb
- spec/helpers/markdown_helper_spec.rb
Change placeholder links to [placeholder-link spans](http://gov-au-ui-kit.apps.staging.digital.gov.au/section-link-styles.html#guide-link-styles-3-placeholder-links) as requested in #415.
Have only implemented for the public markdown renderer, so it won't happen in the editor client-side preview. Am tempted to change to a regex approach, but it was simpler this way re-using code from the spike. And I didn't want [to add another problem](http://regex.info/blog/2006-09-15/247). Thoughts?
> SITES-627 Render placeholder links as placeholder-link spans

- app/controllers/admin/application_controller.rb
- app/controllers/application_controller.rb
- app/controllers/concerns/incomplete_tfa_setup.rb
- spec/features/setup_2fa_spec.rb
- spec/features/signing_in_2fa_spec.rb
Admin users setting up 2FA for the first time can no longer bypass this by going directly to the (default redirect) /admin route.
> [SITES-649] fix admins bypassing 2fa on setup using admin_root_path

- CHANGELOG.md
- app/assets/stylesheets/_content.scss
- app/assets/stylesheets/_news-listing.scss
- app/assets/stylesheets/application.scss
- app/views/departments/index.html.haml
- app/views/feedback/new.html.haml
- app/views/layouts/application.html.haml
- app/views/layouts/news_article.html.haml
- app/views/layouts/section.html.haml
- app/views/layouts/section_home.html.haml
- app/views/ministers/index.html.haml
- app/views/news/index.html.haml
- app/views/templates/root_node.html.haml
- lib/tasks/ui-kit.rake
- spec/fabricators/node.rb
- spec/features/accessibility_spec.rb
This needs the next release of ui-kit to pass the colour contrast tests (this branch has their latest develop). But review comments are welcome now.
Includes:
* re-adding the `tabindex="-1"` attribute to the target of the skip link. Axe-core thinks it's not a valid skip link without it and it's easy enough to disable the focus outline.
* Updating the news list page to use `<h2>` and fixing the CSS so they look like `<h3>`
> Enable best-practice accessibility tests

- .env.sample
- CHANGELOG.md
- app/controllers/confirmations_controller.rb
- app/controllers/editorial/users_controller.rb
- app/forms/user_form.rb
- app/mailers/notifier.rb
- app/models/ability.rb
- app/models/user.rb
- app/views/devise/passwords/edit.html.haml
- app/views/devise/unlocks/new.html.haml
- app/views/editorial/editorial/index.html.haml
- app/views/editorial/users/new.html.haml
- app/views/notifier/user_invite.markerb
- config/breadcrumbs.rb
- config/environments/development.rb
- config/routes.rb
- spec/controllers/confirmations_controller_spec.rb
- spec/controllers/editorial/users_controller_spec.rb
- spec/features/editorial_auth_spec.rb
- spec/mailers/notifier_spec.rb
- spec/mailers/previews/notifier_preview.rb
Creating a new user sends an invite email to the user. When they click the link it sends them to the confirmation page which redirects to the password reset page.
This PR does not remove the registration pages. That's coming later.
> [SITES-647] Allow creating users through editorial

- bin/scrub.rb
Aside from potentially sensitive contents, they're unnecessary when moving between systems.
> Scrub out session table contents

- CHANGELOG.md
- app/views/categories/show.html.haml
This PR closes SITES-675
This PR fixes an issue where the 'Popular now' heading on Category pages was displaying even if there were no Popular now links
> [SITES-675] - Popular now links bug

- CHANGELOG.md
- app/views/templates/custom/school_holidays_act.html.erb
- app/views/templates/custom/school_holidays_nsw.html.erb
- app/views/templates/custom/school_holidays_nt.html.erb
- app/views/templates/custom/school_holidays_qld.html.erb
- app/views/templates/custom/school_holidays_sa.html.erb
- app/views/templates/custom/school_holidays_tas.html.erb
- app/views/templates/custom/school_holidays_vic.html.erb
- app/views/templates/custom/school_holidays_wa.html.erb
This PR replaces the `.highlighted` class on Australian school dates list items with the correct `.highlighted-item` class. 
This fixes the visual defect #463
> Fix highlighted list item visual defect #463

- CHANGELOG.md
- app/controllers/users/two_factor_verification_controller.rb
- app/dashboards/user_dashboard.rb
- app/models/user.rb
- config/initializers/devise.rb
- spec/features/verify_identity_spec.rb
Limits a user's ability to verify their identity with 2FA
> [SITES-643] limit 2fa retries for identity verification

- CHANGELOG.md
- app/controllers/admin/application_controller.rb
- app/controllers/application_controller.rb
- app/controllers/concerns/access_denied_concern.rb
- app/views/errors/unauthorized.html.haml
- spec/concerns/access_denied_concern_spec.rb
- spec/controllers/editorial/editorial_controller_spec.rb
- spec/controllers/editorial/news_controller_spec.rb
- spec/controllers/editorial/nodes_controller_spec.rb
- spec/features/editorial_auth_spec.rb
Authentication behaviour is now handled by using the AccessDeniedConcern
in appropriate controllers. This centralises the behaviour for
consitency. The behaviour is:
- When a user is not authenticated:
If they try to access a page that requires authorisation they will be
redirected to /users/sign_in
If it's a public page the request will succeed
- When a user is authenticated:
If the user is also authorised the request will succeed.
If they are not authorised the request will fail with a 401.
The flash messages are also set by the helper.
I deleted some of the specs for various controllers that were testing
the very rudimentary behaviour of how authentication and authorisation
failures were handled.  The basics are now tested in the spec for the
AccessDeniedConcern itself so I removed the …
> SITES-656 redirect authentication failures to /users/sign_in

- app/views/layouts/root.html.haml
- app/views/templates/root_node.html.haml
This PR removes the dot point from the homepage that described the public release date
> remove release date content from homepage

- CHANGELOG.md
- app/views/templates/_related_ministers.html.haml
> Pluralise 'ministers' only where appropriate

- README.md
- git-secret-patterns.rb
The aws-provider echos personal AWS creds to STDOUT to be used as a
pattern. If it echos no creds (if you have no personal AWS creds) the
response is treated like a pattern that matches EVERYTHING which is not
what we want. The is a bug in git-secrets.
> SITES-712 do not use aws-provider in git secrets

- app/assets/javascripts/application.js
- app/views/application/_ga.html.haml
- app/views/layouts/application.html.haml
This approach guarantees that google analytics calls don't get made before everything has loaded. It also allows the analytics source code to be placed in the asset pipeline.
> Ensure GA tracking is called asynchronously
