Gemfile
Gemfile.lock
app/controllers/admin/topics_controller.rb
app/controllers/editorial/nodes_controller.rb
app/dashboards/agency_dashboard.rb
app/forms/section_home_form.rb
app/models/node.rb
config/locales/en.yml
spec/controllers/admin/topics_controller_spec.rb

- root and section home node types were showing in menu
- admin/agencies/show exception
- editing section home node content (actually this is one I spotted - edit page threw an exception)

Fixes for various bugs from review feedback

---

app/views/application/_tree.html.haml
app/views/templates/section_home.html.haml

As per feedback on https://govausites.atlassian.net/browse/SITES-296

Removed node tree from section home template

---

app/models/concerns/section_heritage.rb
app/models/general_content.rb
app/models/news_article.rb
app/models/node.rb
app/models/root_node.rb
app/models/section_home.rb
app/validators/ancestry_depth_validator.rb
app/validators/non_recursive_ancestry_validator.rb
app/validators/root_protection_validator.rb
app/validators/section_heritage_validator.rb
spec/concerns/section_heritage_spec.rb
spec/controllers/editorial/nodes_controller_spec.rb
spec/fabricators/minister.rb
spec/fabricators/section.rb
spec/features/admin_spec.rb
spec/features/editing_content_spec.rb
spec/features/editorial_navigation_spec.rb
spec/models/node_spec.rb
spec/models/revision_content_spec.rb
spec/models/section_home_spec.rb
spec/validators/ancestry_depth_validator_spec.rb
spec/validators/non_recursive_ancestry_validator_spec.rb
spec/validators/root_protection_validator_spec.rb
spec/validators/section_heritage_validator_spec.rb

As per SITES-375.
Also added a validator to prevent recursive ancestry (SITES-355).

Refactored node validations into classes 

---

app/assets/stylesheets/application.scss

put styling dependencies in import

---

app/controllers/nodes_controller.rb
app/models/news_article.rb
app/models/root_node.rb
app/views/templates/root_node.html.haml
config/routes.rb
db/seeds.rb

Address feedback from QA on homepage

---

CHANGELOG.md
app/controllers/news_controller.rb
app/models/general_content.rb
app/models/news_article.rb
app/views/news/index.html.haml
app/views/templates/root_node.html.haml
config/breadcrumbs.rb
spec/controllers/news_controller_spec.rb
spec/models/node_spec.rb

Provides an aggregation of all news items on `/news`.

[SITES-364] Feature/view news from slash news

---

CHANGELOG.md
README.md
app/controllers/admin/custom_template_nodes_controller.rb
app/controllers/editorial/nodes_controller.rb
app/dashboards/custom_template_node_dashboard.rb
app/decorators/custom_template_node_decorator.rb
app/models/custom_template_node.rb
app/models/node.rb
app/models/section.rb
app/views/templates/custom/public_holidays_qld.html.erb
app/views/templates/custom/public_holidays_tas.html.erb
config/locales/en.yml
config/routes.rb
db/seeds.rb
spec/decorators/custom_template_node_decorator_spec.rb
spec/decorators/node_decorator_spec.rb
spec/fabricators/node.rb
spec/fabricators/section.rb
spec/features/creating_content_spec.rb

This is required scaffolding for the times and dates content, which will be added in future PRs.

[SITES-424] Add a node type for pages with custom templates

---

app/controllers/editorial/news_controller.rb
app/controllers/nodes_controller.rb
app/models/node.rb
app/models/section.rb
config/breadcrumbs.rb
db/seeds.rb
lib/synergy/cms_import.rb
spec/fabricators/revision.rb
spec/fabricators/section.rb
spec/models/section_spec.rb

[SITES-363] Fix/create a news article

---

CHANGELOG.md
app/controllers/editorial/nodes_controller.rb
app/controllers/nodes_controller.rb
app/models/news_article.rb
app/views/templates/root_node.html.haml
app/views/templates/section_home.html.haml
spec/features/section_home_page.rb
spec/models/news_article_spec.rb

If anyone has a good idea on how to test something like this ... would a feature be best?

Display news on Section home pages

---

CHANGELOG.md
app/views/application/_head.html.erb
app/views/layouts/news_article.html.haml
app/views/layouts/section.html.haml
app/views/templates/general_content.html.haml
app/views/templates/news_article.html.haml

Add short_summary to meta description for SEO also.

[SITES-287] Feature/summaries at top of pages

---

CHANGELOG.md
app/models/news_article.rb
db/seeds.rb
spec/models/news_article_spec.rb

Also fixed the news article release_date in seeds.

SITES-475 Validate news article release date

---

CHANGELOG.md
app/views/ministers/index.html.haml
app/views/templates/_related_topics.html.haml

SITES-478 Content changes to ministers index
SITES-486 Link to 'Our Role' beneath related topics

Small static content changes

---

CHANGELOG.md
app/controllers/editorial/news_controller.rb
app/controllers/editorial/nodes_controller.rb
app/controllers/editorial/requests_controller.rb
app/controllers/editorial/sections_controller.rb
app/controllers/editorial/submissions_controller.rb
app/controllers/news_controller.rb
app/controllers/nodes_controller.rb
app/helpers/editorial_helper.rb
app/models/ability.rb
app/views/application/_page_actions.html.haml
app/views/editorial/requests/show.html.haml
app/views/templates/_content_body.html.haml
config/routes.rb
spec/controllers/editorial/section_controller_spec.rb
spec/features/editorial_auth_spec.rb

This includes refactoring the auth tests so it's a little easier to extend for new routes.

[SITES-472] Authorization fixes

---

app/assets/stylesheets/_lists-ie-fix.scss
app/assets/stylesheets/application.scss

This PR ensures the vertical list views render correctly in IE10.
**Before**
**After**

[SITES-545] - IE10 browser fixes

---

CHANGELOG.md
Gemfile
Gemfile.lock
circle.yml

From https://circleci.com/docs/test-metadata/#rspec 
This will give us some detail on the tests running in circle-ci.

Add collecting test metadata

---

app/controllers/application_controller.rb

Development was proving tricky as I had to constantly clear my cache!

Disable etag caching in dev

---

app/controllers/application_controller.rb
app/models/user.rb
app/services/sms_service.rb
config/environments/test.rb
spec/controllers/users/two_factor_setup_controller_spec.rb
spec/features/change_phone_number_spec.rb
spec/features/signing_in_2fa_spec.rb
spec/models/user_spec.rb
spec/services/sms_service_spec.rb

Fixing some bugs in the feature card.
* fixes redirect loop crash on sign_out if 2fa hasn't been done yet
* fixes sms sending for sign_in action

[SITES-590] Bugfix/2fa

---

app/models/section.rb
db/seeds.rb

Fixes SITES-645 but also raised SITES-646 as tech debt.

Fixed seeds data

---

CHANGELOG.md
app/helpers/nodes_helper.rb
app/views/application/_navbar.html.haml
app/views/application/_navbar_part.html.haml

This is another possible solution to #430

[SITES-495] Fix styling of active nodes in sidebar

---

app/views/feedback/create.html.haml
app/views/feedback/new.html.haml
app/views/layouts/application.html.haml
app/views/layouts/news_article.html.haml
app/views/layouts/section.html.haml
app/views/layouts/section_home.html.haml
spec/features/accessibility_spec.rb

Note: The changelog already has an entry covering accessibility

Ensure all content is within an aria landmark

---

CHANGELOG.md
config/initializers/devise.rb

This PR will ensure 2FA is required for _every_ login, and that there is no grace window.

[SITES-664] remove 2fa grace window and force 2fa on every login

---

CHANGELOG.md
app/models/user.rb
config/initializers/devise.rb

Use built-in devise functionality for this.

SITES-630 Timeout sessions after 90 minutes idle

---

app/controllers/admin/application_controller.rb
app/controllers/application_controller.rb
app/services/user_change_logger.rb

+ Refactor application controller for logger session variables to be setup in prviate method

SITES-650 Add user_2fa_failed_attempt event

---

app/views/templates/root_node.html.haml
manifest.yml
spec/features/home_page_spec.rb

feat: remove categories and news links from homepage

---

app/views/application/_feedback_link.html.haml
app/views/layouts/root.html.haml
app/views/templates/root_node.html.haml

ref: change various parts of the homepage copy

---

app/controllers/admin/assets_controller.rb
app/dashboards/asset_dashboard.rb
app/views/templates/section_home.html.haml

This creates support for assets in /admin, which otherwise errors out

fix: add missing admin controller and update user ref in dashboard

---

app/assets/stylesheets/_editor.scss
app/assets/stylesheets/_page_controls.scss
app/helpers/application_helper.rb
app/views/application/_page_actions.html.haml
app/views/application/_signed_in_nav.html.haml
app/views/layouts/application.html.haml

fix: add dropdown to navbar for editorial actions

---

app/controllers/feedback_controller.rb
app/views/feedback/create.html.haml
app/views/feedback/new.html.haml
app/views/layouts/root.html.haml

ref: set feedback to use root layout

---

app/assets/stylesheets/_category-page-popular-now.scss
app/views/layouts/section_home.html.haml
app/views/templates/_abstract.html.haml

ref: style root subpages with root header style

---

app/forms/feedback_form.rb
app/views/feedback/new.html.haml
spec/controllers/feedback_controller_spec.rb

ref: simplify feedback form

---

app/assets/stylesheets/_content_block.scss

Basic flex-box addition for `role=main` because UI-Kit uses just `main`

Fix for sticky footer

---

app/assets/stylesheets/_content_block.scss

Attempting to trouble shoot a layout bug reported on iPhone5 Chrome.

Bugfix: remove flex (possible fix)
